[package]
name = "hermes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29.0", features = ["term", "fs", "ioctl"] }
tokio = { version = "1.39.2", features = ["full", "rt"] }
